---
name: Lint Code Base
on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: super-linter/super-linter@v5.0.0